insert into accounting_transaction_type (description) values ('Depreciation');
insert into accounting_transaction_type (description) values ('Capitalization');
insert into accounting_transaction_type (description) values ('Amortization');
insert into accounting_transaction_type (description) values ('Item Variance Accounting Transaction');
insert into accounting_transaction_type (description) values ('Other Internal Accounting Transaction');
insert into accounting_transaction_type (description) values ('Note');
insert into accounting_transaction_type (description) values ('Tax Due');
insert into accounting_transaction_type (description) values ('Credit Memo');
insert into accounting_transaction_type (description) values ('Credit Line');
insert into accounting_transaction_type (description) values ('Sales Accounting Transaction');
insert into accounting_transaction_type (description) values ('Receipt Accounting Transaction');
insert into accounting_transaction_type (description) values ('Disbursement Accounting Transaction');
